<?php

/**
 * Implements hook_block_info()
 */

function topdest_block_info() {
  $blocks['topdest'] = array(
    'info' => t('Top Destinations'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Custom function to retrieve cities of Places
 */

function topdest_current_city(){
    
      $nids = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->condition('type', 'place', '=')
    ->execute()
    ->fetchCol();
  
  // Get all of the article nodes.
  $result = node_load_multiple($nids);
  
 // foreach ($result as $field) {
      
      //$field = array();
      
      //print_r($field->field_place_country['und'][0]['value']);
      //$country = $field->field_place_country['und'][0]['value'];
      //$city = $field->field_place_city['und'][0]['value'];
 // }
  
return $result;
    
//    $node_type = 'place';
//    $result = db_query("SELECT nid FROM node WHERE type = :nodeType ", array(':nodeType'=>$node_type));
//    print_r($result);
//    return $result;
}

/**
 * Implements hook_block_view()
 */

function topdest_block_view($delta = ''){
    switch($delta) {
        case 'topdest':
            $block['subject'] = t('Top Destinations');
            $result = topdest_current_city();
            //print_r($result->field_place_country['und'][0]['value']);
         $items = array();
               foreach ($result as $node) {  
                   
                   $items[] = array (
                    'data' => l($node->field_place_country['und'][0]['value'], 'node/' .$node->nid),

                    //'data' => $node->field_place_country['und'][0]['value'],
                   // 'data' => $node->field_place_city['und'][0]['value']      
                );
             }
                
            $block['content'] = theme('item_list', array('items' => $items));
            //print_r($items);         
            //$block['content'] = $items[];

            break;
    }
    return $block;
}