<?php

/**
 * Implements hook_permission()
 */

function registration_permission() {
    return array (
        'submit registration' => array (
            'title' => t('Submit registration'),
            'description' => t('Submit the registration form'),
        ),
        'access registration submissions' => array (
            'title' => t('access registration submissions'),
            'description' => t('Access registration form submissions'),
        ),

    );
}

/**
 * Implements hook_menu()
 */

function registration_menu() {
    
    $items = array();
    
    $items['registration'] = array(
        'title'=>'Registration Page',
        'type'=>MENU_NORMAL_ITEM,
        'access arguments'=> array('submit registration'),
        'page callback'=>'drupal_get_form',
        'page arguments'=> array('registration_form'),
    );
     $items['registration-submissions'] = array(
        'title'=>'Registration Sumissions Page',
        'type'=>MENU_NORMAL_ITEM,
        'access arguments'=> array('access registration submissions'),
        'page callback'=>'registration_submissions',
    );
    return $items;
}

/**
 * Registration form
 */

function registration_form($form, &$form_state) {
    
    $form['age'] = array (
        '#type' => 'textfield',
        '#title' =>t('Age'),
        '#size' => 10,
        '#maxlength' => 10,
        '#required' => TRUE,
        '#description' => t('Please enter your age'),
        '#default_value' => '',
    );
    
    $form['firstname'] = array (
        '#type' => 'textfield',
        '#title' =>t('First name'),
        '#size' => 32,
        '#maxlength' => 128,
        '#required' => TRUE,
        '#description' => t('Please enter your first name'),
        '#default_value' => '',
    );
    
    $form['lastname'] = array (
        '#type' => 'textfield',
        '#title' =>t('Last name'),
        '#size' => 50,
        '#maxlength' => 128,
        '#required' => TRUE,
        '#description' => t('Please enter your last name'),
        '#default_value' => '',
    );
    
    $form['summary'] = array (
        '#type' => 'textarea',
        '#title' =>t('Summary'),
        '#description' => t('Provide summary please'),
        '#required' => TRUE,
        '#default_value' => '',
    );
    
     $form['avatar'] = array(
    '#type' => 'managed_file',
    '#name' => 'avatar',
    '#title' => t('Block image'),
    '#size' => 40,
    '#description' => t("Image should be less than 400 pixels wide and in JPG format."),
    '#upload_location' => 'public://'
  );

     
     
    $form['submit'] = array (
        '#type' => 'submit',
        '#value' => t('Add registration'),
    );
    
    return $form;
}

/**
 * Validation of registration form
 */

function registration_form_validate($form, &$form_state) {
    //print('<pre>' . print_r($form_state['values'], 1) . '</pre>'); die();
    if(!is_numeric($form_state['values']['age'])) {
        form_set_error('age', t('You must enter valid age'));
        return FALSE;
    }
    return TRUE;
}

/**
 * Submit handler for inserting data into DB
 */

function registration_form_submit($form, &$form_state) {
    
    $file = file_load($form_state['values']['avatar']);
    
    $file->status = FILE_STATUS_PERMANENT;
    
    $file_saved =file_save($file);
    
        header("Content-Type: image/jpg");
print $file;
    
        // Record that the module is using the file. 
    file_usage_add($file_saved, 'registration', 'avatar', $file_saved->fid); 

    
    $reg_id = db_insert('registration')
            ->fields (array(
                'age' => $form_state['values']['age'],
                'firstname' => $form_state['values']['firstname'],
                'lastname' => $form_state['values']['lastname'],
                'summary' => $form_state['values']['summary'],
                'avatar' => $form_state['values']['avatar'],
            ))
            ->execute();
            drupal_set_message(t('Your registration was submitted'));
}

/**
 * View the registrations
 */

function registration_submissions() {
    //$results = db_query("SELECT * FROM {registration}"); OR
    
    $query = db_select('registration', 'reg');
    $query
            ->fields('reg', array('reg_id', 'age', 'firstname', 'lastname', 'summary', 'avatar'))
            ->range(0,50)
            ->orderBy('reg.reg_id');
    $results = $query->execute();
    $header = array(t('ID'), t('Age'), t('First Name'), t('Last Name'), t('Summary'), t('Avatar'));
    $rows = array();
    
    foreach ($results as $result) {
        $rows[] = array(
            $result->reg_id,
            $result->age,
            $result->firstname,
            $result->lastname,
            $result->summary,
            //print ($result->avatar)
        );
    }
    
    return theme('table', array('header' => $header, 'rows'=>$rows));
}

